### PR TITLE
Set up a "Hello world" project with two apps

### PR DESCRIPTION
**Pull request by Elijahdre**
In this PR, I have :
 - Create a new Rails API app called 'hello-rails-back-end'.
 - Initialize your project with Git.
 - Make sure that your project has a Postgres database set up. 
 - Create a table for storing your messages and create 5 different greetings. 
 - Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).

[Frontend](https://github.com/Elijahdre/hello-react-front-end)

### CODE REVIEW

**Comment by Elijahdre** [comment]
@rloterh Fixed it. Thanks

**Comment by rloterh** [comment]
@Elijahdre 
Running your project with the command `rails s` throws an error.

Tried several other ways but to no avail. No sure of what configurations you implemented

Is there anything I need to do in order run your app?

Standing by

**Comment by Elijahdre** [comment]
@rloterh what kind of error does it throw?

**Comment by rloterh** [comment]
image

**Comment by rloterh** [comment]
Well, let's say that the app does not actually run after the options above are given.

**Comment by Elijahdre** [comment]
@rloterh   I honestly dont know why it appears like that on your end and I can't even figure it out right now because the time is almost up. So I don't know what you can do for me

**Comment by rloterh** [comment]
I tried on different platforms and checked carefully, but it's the same. Checking for what might be the cause, but not getting a definite answer.

If this app is running successfully at your end, then I suggest you raise Zendesk ticket regarding the same.

**Review by rloterh — COMMENTED** [review]
Hi Elijah, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

App is failing to run, with the run command `rails s` after a careful setup and installation on different platforms. Please ensure your app is able to start successfully.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by franclobo — COMMENTED** [review]
Hi @Elijahdre, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

roja

## Invalid Code Review Request

You have submitted the front-end repo project, which doesn't have a professional README file. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo. Please 🙏🏽 add the link to the backend repository in the README.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Elijahdre** [comment]
@franclobo Can you be more explicit because the links were added in the readme. Thank you

**Review by Davidosky007 — COMMENTED** [review]
Hi @Elijahdre 👋 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the frontend repo doesn't have a customized readme file, Kindly customize it to suit your project like you did for your backend  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by franclobo** [comment]
> @franclobo Can you be more explicit because the links were added in the readme. Thank you 

Hi, @Elijahdre what I mean is, please don't forget adding the link at the moment of editing the README file. You should edit the README file with the information of the current project for professional documentation.

**Review by TedLivist — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Elijahdre,

Good job so far!
✔️ Routes are well created
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your frontend app is not implemented. It needs to fetch a random greeting from the backend and display it on the page. Kindly do that. You can refer to this change requested [here](https://github.com/Elijahdre/hello-react-front-end/pull/1#pullrequestreview-1348125736)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @Elijahdre 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔️  App has both frontend and backend repositories correctly linked in readmes 👍🏿 
   

 ## Required Changes ♻️

- [ ] Kindly store your 5 random greetings in your `seeds.rb` in the backend repository, so that when you start your app the seeded database will be displayed, this is part of the requirements and this was also requested by the previous reviewer 👍🏿
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Elijahdre** [comment]
@prolajumokeoni I have completed everything. The reviewer can verify that. I am actually appeal so as not to repeat the final capstone so please conisder when reviewing. Thanks

**Comment by prolajumokeoni** [comment]
Hi @Elijahdre, your [seeds.rb](https://github.com/Elijahdre/hello-rails-back-end/blob/backend/db/seeds.rb) is empty please add it,    this is part of the requirement, this is what you are missing, because there is no greeting in your database a random greeting is not displayed in your React App  


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bobb-Rob — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️

Hi @Elijahdre, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As mentioned by the previous reviewer, you are expected to add atleast five greeting using the `seed.rb` file in the `db` folder. In rails this `seed,rb` file is used to add default data to the database. In other words,  Rails seed files are a useful way of populating a database with the initial data needed for a Rails project. The Rails db/seeds.rb file contains plain Ruby code and can be run with the Rails-default `rails db:seed` task. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ShadyShawkat — APPROVED** [review]
## Hi @Elijahdre, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
